### ISSUE TITLE
No status update if unlocked from third parties

### ISSUE THREAD

**Issue by ecointet** [StefanNienhuis/homebridge-bold#21] opened 2023-08-16 16:54 UTC
If the door is unlocked from the bold app or any other tool, the status is not updated in Homekit.

The integration is nice but only useful if we lock/unlock from the plugin.

is this a normal behavior?

**Comment by StefanNienhuis** [comment] 2023-08-16 17:32
Hi there,

I assume this request has something to so with the unlock activity from iOS 17. While it’d be a nice feature, this would require using the webhook feature from Bold. So currently this is expected behavior.

To use webhooks Bold has to be able to reach your host running HomeBridge, which would likely require port forwarding since most HomeBridge instances are not reachable from the internet.

Another option is using the backend for this communication, but this would be a significant cost per month for me per user. 

I will look into the possibility of using port forwarding, but I doubt many users will be able to use that.

**Comment by kjal203** [comment] 2023-10-02 10:43
Hey Stefan,

I’m experiencing the same issue or behavior. For me „full“ HomeKit integration was the reason to get Bold Connect. 
Can you please explain or point me to resources how to self-host the backend and how to get client id & secret from bold? But that would still require you to implement backend communication, right?

thanks!

**Comment by StefanNienhuis** [comment] 2023-10-02 11:01
Hi,

The repository contains a directory `backend/` that contains the code and deployment configuration for the backend. It's based on the Serverless framework, intended to run on AWS Lambda. You should familiarize yourself with the Serverless framework to deploy this.

The webhooks feature is not implemented in this code though. So you'd have to implement this yourself. If you do, feel free to open a PR to this repo.

Regarding a client id & secret: I'm not sure Bold is actively handing these out, but sending an email with their support form on the website should get it forwarded to the technical department that handles this.

Good luck!

**Comment by kjal203** [comment] 2023-10-02 12:25
Haha, I used to be an integrator and tester but never a developer. I'm not even going to try becoming a coder. 😉 I’ll leave that to the pros.

**Comment by StefanNienhuis** [comment] 2023-12-12 11:32
This might become a feature in the future, but I'm not planning on it anytime soon. Closing as won't fix for now.

**Closed as not planned by StefanNienhuis** 2023-12-12 11:32 UTC
